In [ ]:
# Financial Loan Portfolio & Risk Analysis using Python and Power BI
# 01 - Exploratory Data Analysis (EDA)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_excel("financial_loan.xlsx")

# Display first 5 rows
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [ ]:
df.shape

(38576, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  datetime64[ns]
 8   last_credit_pull_date  38576 non-null  datetime64[ns]
 9   last_payment_date      38576 non-null  datetime64[ns]
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  datetime64[ns]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(5), object(11)
memory usage: 7.1+ MB

In [ ]:
df.isnull().sum()

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

emp_title                3.727706
id                       0.000000
application_type         0.000000
address_state            0.000000
emp_length               0.000000
grade                    0.000000
home_ownership           0.000000
issue_date               0.000000
last_credit_pull_date    0.000000
last_payment_date        0.000000
loan_status              0.000000
next_payment_date        0.000000
member_id                0.000000
purpose                  0.000000
sub_grade                0.000000
term                     0.000000
verification_status      0.000000
annual_income            0.000000
dti                      0.000000
installment              0.000000
int_rate                 0.000000
loan_amount              0.000000
total_acc                0.000000
total_payment            0.000000
dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['id'].duplicated().sum()

np.int64(0)

In [ ]:
df['loan_status'].value_counts()

loan_status
Fully Paid     32145
Charged Off     5333
Current         1098
Name: count, dtype: int64

In [ ]:
df.dtypes

id                                int64
address_state                    object
application_type                 object
emp_length                       object
emp_title                        object
grade                            object
home_ownership                   object
issue_date               datetime64[ns]
last_credit_pull_date    datetime64[ns]
last_payment_date        datetime64[ns]
loan_status                      object
next_payment_date        datetime64[ns]
member_id                         int64
purpose                          object
sub_grade                        object
term                             object
verification_status              object
annual_income                   float64
dti                             float64
installment                     float64
int_rate                        float64
loan_amount                       int64
total_acc                         int64
total_payment                     int64
dtype: object

In [ ]:
date_columns = [
    'issue_date',
    'last_credit_pull_date',
    'last_payment_date',
    'next_payment_date'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [ ]:
df[date_columns].dtypes

issue_date               datetime64[ns]
last_credit_pull_date    datetime64[ns]
last_payment_date        datetime64[ns]
next_payment_date        datetime64[ns]
dtype: object

In [ ]:
#Clean the columns
df['emp_title'] = df['emp_title'].fillna('Unknown')

In [ ]:
df['emp_title'].isnull().sum()

np.int64(0)

In [ ]:
# Convert emp_length
df['emp_length_years'] = (
    df['emp_length']
    .str.replace(' years', '', regex=False)
    .str.replace(' year', '', regex=False)
    .str.replace('+', '', regex=False)
    .str.replace('< 1', '0', regex=False)
    .astype(float)
)

In [ ]:
df[['emp_length', 'emp_length_years']].head(10)

  emp_length  emp_length_years
0   < 1 year               0.0
1    9 years               9.0
2    4 years               4.0
3   < 1 year               0.0
4  10+ years              10.0
5    3 years               3.0
6  10+ years              10.0
7  10+ years              10.0
8  10+ years              10.0
9  10+ years              10.0

In [ ]:
df['term_months'] = (
    df['term']
    .str.replace(' months', '', regex=False)
    .astype(int)
)

In [ ]:
df['issue_year'] = df['issue_date'].dt.year
df['issue_month'] = df['issue_date'].dt.month
df['issue_month_name'] = df['issue_date'].dt.month_name()

In [ ]:
df[['issue_date', 'issue_year', 'issue_month', 'issue_month_name']].head()

  issue_date  issue_year  issue_month issue_month_name
0 2021-02-11        2021            2         February
1 2021-01-01        2021            1          January
2 2021-01-05        2021            1          January
3 2021-02-25        2021            2         February
4 2021-01-01        2021            1          January

In [ ]:
df['default_flag'] = np.where(
    df['loan_status'] == 'Charged Off',
    1,
    0
)

In [ ]:
default_rate = df['default_flag'].mean() * 100

print(f"Default Rate: {default_rate:.2f}%")

Default Rate: 13.82%

In [ ]:
numeric_columns = [
    'annual_income',
    'dti',
    'installment',
    'int_rate',
    'loan_amount',
    'total_acc',
    'total_payment'
]

df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
annual_income,38576.0,69644.540310,64293.681045,4000.0000,41500.0000,60000.0000,83200.5000,6.000000e+06
dti,38576.0,0.133274,0.066662,0.0000,0.0821,0.1342,0.1859,2.999000e-01
installment,38576.0,326.862965,209.092000,15.6900,168.4500,283.0450,434.4425,1.305190e+03
int_rate,38576.0,0.120488,0.037164,0.0542,0.0932,0.1186,0.1459,2.459000e-01
loan_amount,38576.0,11296.066855,7460.746022,500.0000,5500.0000,10000.0000,15000.0000,3.500000e+04
total_acc,38576.0,22.132544,11.392282,2.0000,14.0000,20.0000,29.0000,9.000000e+01
total_payment,38576.0,12263.348533,9051.104777,34.0000,5633.0000,10042.0000,16658.0000,5.856400e+04

In [ ]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
annual_income,38576.0,69644.540310,64293.681045,4000.0000,41500.0000,60000.0000,83200.5000,6.000000e+06
dti,38576.0,0.133274,0.066662,0.0000,0.0821,0.1342,0.1859,2.999000e-01
installment,38576.0,326.862965,209.092000,15.6900,168.4500,283.0450,434.4425,1.305190e+03
int_rate,38576.0,0.120488,0.037164,0.0542,0.0932,0.1186,0.1459,2.459000e-01
loan_amount,38576.0,11296.066855,7460.746022,500.0000,5500.0000,10000.0000,15000.0000,3.500000e+04
total_acc,38576.0,22.132544,11.392282,2.0000,14.0000,20.0000,29.0000,9.000000e+01
total_payment,38576.0,12263.348533,9051.104777,34.0000,5633.0000,10042.0000,16658.0000,5.856400e+04

In [ ]:
df['emp_length_years'].value_counts().sort_index()

emp_length_years
0.0     4575
1.0     3229
2.0     4382
3.0     4088
4.0     3428
5.0     3273
6.0     2228
7.0     1772
8.0     1476
9.0     1255
10.0    8870
Name: count, dtype: int64

In [ ]:
#Data Cleaning & Preparation


# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              38576 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  datetime64[ns]
 8   last_credit_pull_date  38576 non-null  datetime64[ns]
 9   last_payment_date      38576 non-null  datetime64[ns]
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  datetime64[ns]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
 24  emp_length_years       38576 non-null  float64
 25  term_months            38576 non-null  int64
 26  issue_year             38576 non-null  int32
 27  issue_month            38576 non-null  int32
 28  issue_month_name       38576 non-null  object
 29  default_flag           38576 non-null  int64
dtypes: datetime64[ns](4), float64(5), int32(2), int64(7), object(12)
memory usage: 8.5+ MB

In [ ]:
df.dtypes

id                                int64
address_state                    object
application_type                 object
emp_length                       object
emp_title                        object
grade                            object
home_ownership                   object
issue_date               datetime64[ns]
last_credit_pull_date    datetime64[ns]
last_payment_date        datetime64[ns]
loan_status                      object
next_payment_date        datetime64[ns]
member_id                         int64
purpose                          object
sub_grade                        object
term                             object
verification_status              object
annual_income                   float64
dti                             float64
installment                     float64
int_rate                        float64
loan_amount                       int64
total_acc                         int64
total_payment                     int64
emp_length_years                float64
term_months                       int64
issue_year                        int32
issue_month                       int32
issue_month_name                 object
default_flag                      int64
dtype: object

In [ ]:
df.groupby(['loan_status', 'default_flag']).size().reset_index(name='count')

   loan_status  default_flag  count
0  Charged Off             1   5333
1      Current             0   1098
2   Fully Paid             0  32145

In [ ]:
df['default_flag'].value_counts()

default_flag
0    33243
1     5333
Name: count, dtype: int64

In [ ]:
df['default_flag'].value_counts(normalize=True) * 100

default_flag
0    86.175342
1    13.824658
Name: proportion, dtype: float64

In [ ]:
#Exploratory Data Analysis (EDA)
df['loan_amount'].describe()

count    38576.000000
mean     11296.066855
std       7460.746022
min        500.000000
25%       5500.000000
50%      10000.000000
75%      15000.000000
max      35000.000000
Name: loan_amount, dtype: float64

In [ ]:
df['annual_income'].describe()

count    3.857600e+04
mean     6.964454e+04
std      6.429368e+04
min      4.000000e+03
25%      4.150000e+04
50%      6.000000e+04
75%      8.320050e+04
max      6.000000e+06
Name: annual_income, dtype: float64

In [ ]:
df['int_rate'].describe()

count    38576.000000
mean         0.120488
std          0.037164
min          0.054200
25%          0.093200
50%          0.118600
75%          0.145900
max          0.245900
Name: int_rate, dtype: float64

In [ ]:
df['dti'].describe()

count    38576.000000
mean         0.133274
std          0.066662
min          0.000000
25%          0.082100
50%          0.134200
75%          0.185900
max          0.299900
Name: dti, dtype: float64

In [ ]:
df.groupby('default_flag')[[
    'loan_amount',
    'annual_income',
    'int_rate',
    'dti',
    'installment',
    'total_payment'
]].mean()

,loan_amount,annual_income,int_rate,dti,installment,total_payment
default_flag,,,,,,
0,11136.926571,70627.753460,0.117553,0.132188,324.630637,13109.110790
1,12288.060191,63515.728245,0.138786,0.140047,340.778076,6991.330021

In [ ]:
pd.crosstab(
    df['grade'],
    df['default_flag'],
    normalize='index'
).round(4) * 100

default_flag      0      1
grade
A             94.30   5.70
B             88.50  11.50
C             83.98  16.02
D             79.31  20.69
E             75.20  24.80
F             69.75  30.25
G             68.69  31.31